name: "Return first file that exists"
description: "Check given list of files in order and return first on that exists."

inputs:
  files:
    type: string
    description: "Space-separated list of files to check in order"
    required: true

outputs:
  found_file:
    description: "Path of first file found."
    value: ${{ steps.find-file.outputs.found_file }}

runs:
  using: "composite"
  steps:
    - name: Get file list
      id: file-list
      shell: bash
      run: |
        files=$(printf %s "${{ inputs.files }}" | tr '\n' ' ')
        echo "Will search: ${files}"
        echo "files=${files}" >> "$GITHUB_OUTPUT"

    - name: Check file list
      id: find-file
      shell: bash
      run: |
        for f in ${{ steps.file-list.outputs.files }}; do
          if [[ -e "${f}" ]]; then
            found_file="${f}"
            break
          fi
        done

        echo "found_file=${found_file}"
        echo "found_file=${found_file}" >> "$GITHUB_OUTPUT"
