# Changes here will be overwritten by Copier
_commit: v0.15.7-7-g6877dda
_src_path: https://github.com/navapbc/template-infra
base_code_repository_url: git@github.com:navapbc/platform-test.git
base_default_region: us-east-1
base_owner: platform-admins
base_project_name: platform-test
template: base
