plugins:
  - rubocop-rspec
inherit_gem:
  pundit: config/rubocop-rspec.yml
  rubocop-rails-omakase: rubocop.yml

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NoExpectationExample:
  AllowedPatterns:
    - assert_
    - is_expected_in_block
