plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
inherit_gem:
  pundit: config/rubocop-rspec.yml
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: disable

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NoExpectationExample:
  AllowedPatterns:
    - assert_
    - is_expected_in_block

RSpecRails/HttpStatusNameConsistency:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
