services:
  app-rails-database:
    image: postgres:14-alpine
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    environment:
      POSTGRES_PASSWORD: secret123
      POSTGRES_USER: app
    healthcheck:
      test: "pg_isready --username=app"
      timeout: 10s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - app-rails-database_data:/var/lib/postgresql/data

  # Rails app
  # Configured for "development" RAILS_ENV
  app-rails:
    build:
      context: .
      target: dev
    depends_on:
      app-rails-database:
        condition: service_healthy
    env_file: .env
    environment:
      - DB_HOST=app-rails-database
      - RAILS_BINDING=0.0.0.0
      - RAILS_ENV=development
    ports:
      - 3100:3100
    volumes:
      - .:/rails
      # Use named volumes for directories that the container should use the guest
      # machine's dir instead of the host machine's dir, which may be divergent.
      # This is especially true for any dependency or temp directories.
      - app-rails_nodemodules:/rails/node_modules
      - app-rails_tmp:/rails/tmp
      - app-rails_storage:/rails/storage

volumes:
  app-rails-database_data:
  app-rails_nodemodules:
  app-rails_tmp:
  app-rails_storage:
