environment_name                = "dev"
load_balancer_security_group_id = "sg-0f5ecd8d2b8acd638"
service_security_group_id       = "sg-045044fb164a7e2fe"
tfstate_bucket                  = "platform-test-430004246987-us-east-1-tf-state"
tfstate_key                     = "infra/app/service/dev.tfstate"
region                          = "us-east-1"
