environment_name = "dev"
dns_zone         = "platform-test.navateam.com"
tfstate_bucket   = "platform-test-430004246987-us-east-1-tf"
tfstate_key      = "infra/app/service/dev.tfstate"
region           = "us-east-1"
