environment_name     = "<ENVIRONMENT>"
tfstate_bucket       = "<TF_STATE_BUCKET_NAME>"
tfstate_key          = "<TF_STATE_KEY>"
region               = "<REGION>"
db_access_policy_arn = "<DB_ACCESS_POLICY_ARN>"
db_service_env_vars  = "<DB_SERVICE_ENV_VARS>"
