(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Date_internal" "*external*" with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Date_internal, it may need recompiling"
module Date_internal = Date_internal
let () =
  match Catala_runtime.check_module "List_fr" "CM0|15e33851|32e49b03|19e8ab0c"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module List_fr, it may need recompiling"
module List_fr = List_fr

module Mois = struct
  type t =
    | Janvier
    | Fevrier
    | Mars
    | Avril
    | Mai
    | Juin
    | Juillet
    | Aout
    | Septembre
    | Octobre
    | Novembre
    | Decembre
end

module Jour_de_la_semaine = struct
  type t = Lundi | Mardi | Mercredi | Jeudi | Vendredi | Samedi | Dimanche
end


(* Toplevel def min *)
let min : date -> date -> date =
  fun (d1: date) (d2: date) ->  if (o_lte_dat_dat d1 d2) then d1 else d2

(* Toplevel def max *)
let max : date -> date -> date =
  fun (d1: date) (d2: date) ->  if (o_gte_dat_dat d1 d2) then d1 else d2

(* Toplevel def depuis_année_mois_jour *)
let depuis_annee_mois_jour : code_location -> integer -> integer ->
                               integer -> date =
  fun (pos: code_location) (dannee: integer) (dmois: integer)
    (djour: integer) -> (Date_internal.of_ymd) pos dannee dmois djour

(* Toplevel def vers_année_mois_jour *)
let vers_annee_mois_jour : date -> (integer * integer * integer) =
  fun (d: date) -> (Date_internal.to_ymd) d

(* Toplevel def dernier_jour_du_mois *)
let dernier_jour_du_mois : date -> date =
  fun (d: date) -> (Date_internal.last_day_of_month) d

(* Toplevel def mois_vers_entier *)
let mois_vers_entier : Mois.t -> integer =
  fun (m: Mois.t) ->
    match m
    with
    | Mois.Janvier -> (integer_of_string "1")
    | Mois.Fevrier -> (integer_of_string "2")
    | Mois.Mars -> (integer_of_string "3")
    | Mois.Avril -> (integer_of_string "4")
    | Mois.Mai -> (integer_of_string "5")
    | Mois.Juin -> (integer_of_string "6")
    | Mois.Juillet -> (integer_of_string "7")
    | Mois.Aout -> (integer_of_string "8")
    | Mois.Septembre -> (integer_of_string "9")
    | Mois.Octobre -> (integer_of_string "10")
    | Mois.Novembre -> (integer_of_string "11")
    | Mois.Decembre -> (integer_of_string "12")

(* Toplevel def entier_vers_mois *)
let entier_vers_mois : code_location -> integer -> Mois.t =
  fun (pos: code_location) (i: integer) ->
     if (o_eq_int_int i (integer_of_string "1")) then (Mois.Janvier) else
      ( if (o_eq_int_int i (integer_of_string "2")) then (Mois.Fevrier)
         else
         ( if (o_eq_int_int i (integer_of_string "3")) then (Mois.Mars)
            else
            ( if (o_eq_int_int i (integer_of_string "4")) then
               (Mois.Avril) else
               ( if (o_eq_int_int i (integer_of_string "5")) then
                  (Mois.Mai) else
                  ( if (o_eq_int_int i (integer_of_string "6")) then
                     (Mois.Juin) else
                     ( if (o_eq_int_int i (integer_of_string "7")) then
                        (Mois.Juillet) else
                        ( if (o_eq_int_int i (integer_of_string "8"))
                           then (Mois.Aout) else
                           ( if (o_eq_int_int i (integer_of_string "9"))
                              then (Mois.Septembre) else
                              ( if
                                 (o_eq_int_int i (integer_of_string "10"))
                                 then (Mois.Octobre) else
                                 ( if
                                    (o_eq_int_int i (integer_of_string
                                       "11")) then (Mois.Novembre) else
                                    ( if
                                       (o_eq_int_int i (integer_of_string
                                          "12")) then (Mois.Decembre)
                                       else
                                       (let _ : date =
                                          ((Date_internal.of_ymd) pos
                                             (integer_of_string "-1")
                                             (integer_of_string "-1")
                                             (integer_of_string "-1")) in
                                         (raise
                                         (Error (Impossible, [{filename="libcatala/date_fr.catala_fr";
                                                               start_line=172; start_column=65;
                                                               end_line=172; end_column=75;
                                                               law_headings=
                                                               ["Mois nommés";
                                                                 "Dates"]}], None)))))))))))))))

(* Toplevel def est_assez_âgé_arrondi_inférieur *)
let est_assez_age_arrondi_inferieur : date -> duration -> date -> bool =
  fun (date_de_naissance: date) (age: duration) (a_date: date) ->
    o_gte_dat_dat a_date
      ((Date_internal.add_rounded_down) date_de_naissance age)

(* Toplevel def est_assez_âgé_arrondi_supérieur *)
let est_assez_age_arrondi_superieur : date -> duration -> date -> bool =
  fun (date_de_naissance: date) (age: duration) (a_date: date) ->
    o_gte_dat_dat a_date
      ((Date_internal.add_rounded_up) date_de_naissance age)

(* Toplevel def dernier_jour_de_l_année *)
let dernier_jour_de_l_annee : date -> date =
  fun (d: date) ->
    (let ymd : (integer * integer * integer) = (vers_annee_mois_jour d)
    in
    (depuis_annee_mois_jour
       ({filename="libcatala/date_fr.catala_fr";
         start_line=112; start_column=5; end_line=112; end_column=27;
         law_headings=["Aller vers le passé ou le futur"; "Dates"]})
       (let x, _, _ = ymd in x) (integer_of_string "12")
       (integer_of_string "31")))

(* Toplevel def premier_jour_de_l_année *)
let premier_jour_de_l_annee : date -> date =
  fun (d: date) ->
    (let ymd : (integer * integer * integer) = (vers_annee_mois_jour d)
    in
    (depuis_annee_mois_jour
       ({filename="libcatala/date_fr.catala_fr";
         start_line=103; start_column=5; end_line=103; end_column=27;
         law_headings=["Aller vers le passé ou le futur"; "Dates"]})
       (let x, _, _ = ymd in x) (integer_of_string "1")
       (integer_of_string "1")))

(* Toplevel def premier_jour_du_mois *)
let premier_jour_du_mois : date -> date =
  fun (d: date) ->
    (let ymd : (integer * integer * integer) = (vers_annee_mois_jour d)
    in
    (depuis_annee_mois_jour
       ({filename="libcatala/date_fr.catala_fr";
         start_line=86; start_column=5; end_line=86; end_column=27;
         law_headings=["Aller vers le passé ou le futur"; "Dates"]})
       (let x, _, _ = ymd in x) (let _, x, _ = ymd in x)
       (integer_of_string "1")))

(* Toplevel def accès_jour *)
let acces_jour : date -> integer =
  fun (d: date) -> let _, _, x = (vers_annee_mois_jour d) in x

(* Toplevel def accès_mois *)
let acces_mois : date -> integer =
  fun (d: date) -> let _, x, _ = (vers_annee_mois_jour d) in x

(* Toplevel def accès_année *)
let acces_annee : date -> integer =
  fun (d: date) -> let x, _, _ = (vers_annee_mois_jour d) in x

(* Toplevel def est_assez_jeune_arrondi_inférieur *)
let est_assez_jeune_arrondi_inferieur : date -> duration -> date -> bool =
  fun (date_de_naissance: date) (age: duration) (a_date: date) ->
    o_not (est_assez_age_arrondi_inferieur date_de_naissance age a_date)

(* Toplevel def est_assez_jeune_arrondi_supérieur *)
let est_assez_jeune_arrondi_superieur : date -> duration -> date -> bool =
  fun (date_de_naissance: date) (age: duration) (a_date: date) ->
    o_not (est_assez_age_arrondi_superieur date_de_naissance age a_date)

(* Toplevel def jour_de_la_semaine *)
let jour_de_la_semaine : date -> Jour_de_la_semaine.t =
  fun (date_donnee: date) ->
    (let month_number : integer = (acces_mois date_donnee) in
    (let year_number : integer =
       ( if (o_lt_int_int month_number (integer_of_string "3")) then
          (o_sub_int_int (acces_annee date_donnee) (integer_of_string
             "1")) else (acces_annee date_donnee)) in
    (let n_number : integer =
       (match
          ((List_fr.nieme_element)
             ([|(integer_of_string "0"); (integer_of_string "3");
                (integer_of_string "2"); (integer_of_string "5");
                (integer_of_string "0"); (integer_of_string "3");
                (integer_of_string "5"); (integer_of_string "1");
                (integer_of_string "4"); (integer_of_string "6");
                (integer_of_string "2"); (integer_of_string "4")|])
             month_number)
        with
        | Optional.Absent -> (raise
            (Error (Impossible, [{filename="libcatala/date_fr.catala_fr";
                                  start_line=273; start_column=16;
                                  end_line=273; end_column=26;
                                  law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)";
                                                 "Dates"]}], None)))
        | Optional.Present n -> n) in
    (let day_number : integer =
       (o_sub_int_int
          (o_add_int_int
             (o_add_int_int
                (o_add_int_int
                   (o_sub_int_int
                      (o_add_int_int year_number
                         (o_toint_rat
                            (o_div_int_int
                               {filename="libcatala/date_fr.catala_fr";
                                start_line=277; start_column=33;
                                end_line=277; end_column=34;
                                law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)";
                                               "Dates"]} year_number
                               (integer_of_string "4"))))
                      (o_toint_rat
                         (o_div_int_int
                            {filename="libcatala/date_fr.catala_fr";
                             start_line=278; start_column=33;
                             end_line=278; end_column=36;
                             law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)";
                                            "Dates"]} year_number
                            (integer_of_string "100"))))
                   (o_toint_rat
                      (o_div_int_int
                         {filename="libcatala/date_fr.catala_fr";
                          start_line=279; start_column=33;
                          end_line=279; end_column=36;
                          law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)";
                                         "Dates"]} year_number
                         (integer_of_string "400")))) n_number)
             (acces_jour date_donnee))
          (o_mult_int_int (integer_of_string "7")
             (o_toint_rat
                (o_div_int_int
                   {filename="libcatala/date_fr.catala_fr";
                    start_line=289; start_column=9;
                    end_line=289; end_column=10;
                    law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)";
                                   "Dates"]}
                   (o_add_int_int
                      (o_add_int_int
                         (o_add_int_int
                            (o_sub_int_int
                               (o_add_int_int year_number
                                  (o_toint_rat
                                     (o_div_int_int
                                        {filename="libcatala/date_fr.catala_fr";
                                         start_line=284; start_column=35;
                                         end_line=284; end_column=36;
                                         law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)";
                                                        "Dates"]}
                                        year_number (integer_of_string
                                        "4"))))
                               (o_toint_rat
                                  (o_div_int_int
                                     {filename="libcatala/date_fr.catala_fr";
                                      start_line=285; start_column=35;
                                      end_line=285; end_column=38;
                                      law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)";
                                                     "Dates"]}
                                     year_number (integer_of_string
                                     "100"))))
                            (o_toint_rat
                               (o_div_int_int
                                  {filename="libcatala/date_fr.catala_fr";
                                   start_line=286; start_column=35;
                                   end_line=286; end_column=38;
                                   law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)";
                                                  "Dates"]} year_number
                                  (integer_of_string "400")))) n_number)
                      (acces_jour date_donnee)) (integer_of_string "7")))))
    in
    (match
       ((List_fr.nieme_element)
          ([|(Jour_de_la_semaine.Lundi); (Jour_de_la_semaine.Mardi);
             (Jour_de_la_semaine.Mercredi); (Jour_de_la_semaine.Jeudi);
             (Jour_de_la_semaine.Vendredi); (Jour_de_la_semaine.Samedi);
             (Jour_de_la_semaine.Dimanche)|])
          (o_add_int_int day_number (integer_of_string "1")))
     with
     | Optional.Absent -> (raise
         (Error (Impossible, [{filename="libcatala/date_fr.catala_fr";
                               start_line=294; start_column=14;
                               end_line=294; end_column=24;
                               law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)";
                                              "Dates"]}], None)))
     | Optional.Present d -> d)))))

let () =
  Catala_runtime.register_module "Date_fr"
    [ "min", Stdlib.Obj.repr min;
      "max", Stdlib.Obj.repr max;
      "depuis_ann\195\169e_mois_jour",
        Stdlib.Obj.repr depuis_annee_mois_jour;
      "vers_ann\195\169e_mois_jour", Stdlib.Obj.repr vers_annee_mois_jour;
      "dernier_jour_du_mois", Stdlib.Obj.repr dernier_jour_du_mois;
      "mois_vers_entier", Stdlib.Obj.repr mois_vers_entier;
      "entier_vers_mois", Stdlib.Obj.repr entier_vers_mois;
      "est_assez_\195\162g\195\169_arrondi_inf\195\169rieur",
        Stdlib.Obj.repr est_assez_age_arrondi_inferieur;
      "est_assez_\195\162g\195\169_arrondi_sup\195\169rieur",
        Stdlib.Obj.repr est_assez_age_arrondi_superieur;
      "dernier_jour_de_l_ann\195\169e",
        Stdlib.Obj.repr dernier_jour_de_l_annee;
      "premier_jour_de_l_ann\195\169e",
        Stdlib.Obj.repr premier_jour_de_l_annee;
      "premier_jour_du_mois", Stdlib.Obj.repr premier_jour_du_mois;
      "acc\195\168s_jour", Stdlib.Obj.repr acces_jour;
      "acc\195\168s_mois", Stdlib.Obj.repr acces_mois;
      "acc\195\168s_ann\195\169e", Stdlib.Obj.repr acces_annee;
      "est_assez_jeune_arrondi_inf\195\169rieur",
        Stdlib.Obj.repr est_assez_jeune_arrondi_inferieur;
      "est_assez_jeune_arrondi_sup\195\169rieur",
        Stdlib.Obj.repr est_assez_jeune_arrondi_superieur;
      "jour_de_la_semaine", Stdlib.Obj.repr jour_de_la_semaine ]
    "CM0|15e33851|32e49b03|3096d497"
