(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Date_internal" "*external*" with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Date_internal, it may need recompiling"
module Date_internal = Date_internal
let () =
  match Catala_runtime.check_module "List_en" "CM0|15e33851|32e49b03|24a3fb7d"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module List_en, it may need recompiling"
module List_en = List_en

module Month = struct
  type t =
    | January
    | February
    | March
    | April
    | May
    | June
    | July
    | August
    | September
    | October
    | November
    | December
end

module Day_of_week = struct
  type t =
    | Monday
    | Tuesday
    | Wednesday
    | Thursday
    | Friday
    | Saturday
    | Sunday
end


(* Toplevel def min *)
let min : date -> date -> date =
  fun (d1: date) (d2: date) ->  if (o_lte_dat_dat d1 d2) then d1 else d2

(* Toplevel def max *)
let max : date -> date -> date =
  fun (d1: date) (d2: date) ->  if (o_gte_dat_dat d1 d2) then d1 else d2

(* Toplevel def of_year_month_day *)
let of_year_month_day : code_location -> integer -> integer -> integer ->
                          date =
  fun (pos: code_location) (dyear: integer) (dmonth: integer)
    (dday: integer) -> (Date_internal.of_ymd) pos dyear dmonth dday

(* Toplevel def to_year_month_day *)
let to_year_month_day : date -> (integer * integer * integer) =
  fun (d: date) -> (Date_internal.to_ymd) d

(* Toplevel def last_day_of_month *)
let last_day_of_month : date -> date =
  fun (d: date) -> (Date_internal.last_day_of_month) d

(* Toplevel def month_to_integer *)
let month_to_integer : Month.t -> integer =
  fun (m: Month.t) ->
    match m
    with
    | Month.January -> (integer_of_string "1")
    | Month.February -> (integer_of_string "2")
    | Month.March -> (integer_of_string "3")
    | Month.April -> (integer_of_string "4")
    | Month.May -> (integer_of_string "5")
    | Month.June -> (integer_of_string "6")
    | Month.July -> (integer_of_string "7")
    | Month.August -> (integer_of_string "8")
    | Month.September -> (integer_of_string "9")
    | Month.October -> (integer_of_string "10")
    | Month.November -> (integer_of_string "11")
    | Month.December -> (integer_of_string "12")

(* Toplevel def integer_to_month *)
let integer_to_month : code_location -> integer -> Month.t =
  fun (pos: code_location) (i: integer) ->
     if (o_eq_int_int i (integer_of_string "1")) then (Month.January) else
      ( if (o_eq_int_int i (integer_of_string "2")) then (Month.February)
         else
         ( if (o_eq_int_int i (integer_of_string "3")) then (Month.March)
            else
            ( if (o_eq_int_int i (integer_of_string "4")) then (Month.April)
               else
               ( if (o_eq_int_int i (integer_of_string "5")) then (Month.May)
                  else
                  ( if (o_eq_int_int i (integer_of_string "6")) then
                     (Month.June) else
                     ( if (o_eq_int_int i (integer_of_string "7")) then
                        (Month.July) else
                        ( if (o_eq_int_int i (integer_of_string "8")) then
                           (Month.August) else
                           ( if (o_eq_int_int i (integer_of_string "9")) then
                              (Month.September) else
                              ( if (o_eq_int_int i (integer_of_string "10"))
                                 then (Month.October) else
                                 ( if
                                    (o_eq_int_int i (integer_of_string "11"))
                                    then (Month.November) else
                                    ( if
                                       (o_eq_int_int i (integer_of_string
                                          "12")) then (Month.December) else
                                       (let _ : date =
                                          ((Date_internal.of_ymd) pos
                                             (integer_of_string "-1")
                                             (integer_of_string "-1")
                                             (integer_of_string "-1")) in
                                         (raise
                                         (Error (Impossible, [{filename="libcatala/date_en.catala_en";
                                                               start_line=171; start_column=60;
                                                               end_line=171; end_column=70;
                                                               law_headings=
                                                               ["Named months";
                                                                 "Dates"]}], None)))))))))))))))

(* Toplevel def is_old_enough_rounding_down *)
let is_old_enough_rounding_down : date -> duration -> date -> bool =
  fun (birth_date: date) (age: duration) (at_date: date) ->
    o_gte_dat_dat at_date ((Date_internal.add_rounded_down) birth_date age)

(* Toplevel def is_old_enough_rounding_up *)
let is_old_enough_rounding_up : date -> duration -> date -> bool =
  fun (birth_date: date) (age: duration) (at_date: date) ->
    o_gte_dat_dat at_date ((Date_internal.add_rounded_up) birth_date age)

(* Toplevel def last_day_of_year *)
let last_day_of_year : date -> date =
  fun (d: date) ->
    (let ymd : (integer * integer * integer) = (to_year_month_day d) in
    (of_year_month_day
       ({filename="libcatala/date_en.catala_en";
         start_line=111; start_column=5; end_line=111; end_column=22;
         law_headings=["Getting to the past or future"; "Dates"]}) (let x, _,
       _ = ymd in x) (integer_of_string "12") (integer_of_string "31")))

(* Toplevel def first_day_of_year *)
let first_day_of_year : date -> date =
  fun (d: date) ->
    (let ymd : (integer * integer * integer) = (to_year_month_day d) in
    (of_year_month_day
       ({filename="libcatala/date_en.catala_en";
         start_line=102; start_column=5; end_line=102; end_column=22;
         law_headings=["Getting to the past or future"; "Dates"]}) (let x, _,
       _ = ymd in x) (integer_of_string "1") (integer_of_string "1")))

(* Toplevel def first_day_of_month *)
let first_day_of_month : date -> date =
  fun (d: date) ->
    (let ymd : (integer * integer * integer) = (to_year_month_day d) in
    (of_year_month_day
       ({filename="libcatala/date_en.catala_en";
         start_line=85; start_column=5; end_line=85; end_column=22;
         law_headings=["Getting to the past or future"; "Dates"]}) (let x, _,
       _ = ymd in x) (let _, x, _ = ymd in x) (integer_of_string "1")))

(* Toplevel def get_day *)
let get_day : date -> integer =
  fun (d: date) -> let _, _, x = (to_year_month_day d) in x

(* Toplevel def get_month *)
let get_month : date -> integer =
  fun (d: date) -> let _, x, _ = (to_year_month_day d) in x

(* Toplevel def get_year *)
let get_year : date -> integer =
  fun (d: date) -> let x, _, _ = (to_year_month_day d) in x

(* Toplevel def is_young_enough_rounding_down *)
let is_young_enough_rounding_down : date -> duration -> date -> bool =
  fun (birth_date: date) (age: duration) (at_date: date) ->
    o_not (is_old_enough_rounding_down birth_date age at_date)

(* Toplevel def is_young_enough_rounding_up *)
let is_young_enough_rounding_up : date -> duration -> date -> bool =
  fun (birth_date: date) (age: duration) (at_date: date) ->
    o_not (is_old_enough_rounding_up birth_date age at_date)

(* Toplevel def day_of_week *)
let day_of_week : date -> Day_of_week.t =
  fun (given_date: date) ->
    (let month_number : integer = (get_month given_date) in
    (let year_number : integer =
       ( if (o_lt_int_int month_number (integer_of_string "3")) then
          (o_sub_int_int (get_year given_date) (integer_of_string "1")) else
          (get_year given_date)) in
    (let n_number : integer =
       (match
          ((List_en.nth_element)
             ([|(integer_of_string "0"); (integer_of_string "3");
                (integer_of_string "2"); (integer_of_string "5");
                (integer_of_string "0"); (integer_of_string "3");
                (integer_of_string "5"); (integer_of_string "1");
                (integer_of_string "4"); (integer_of_string "6");
                (integer_of_string "2"); (integer_of_string "4")|])
             month_number)
        with
        | Optional.Absent -> (raise
            (Error (Impossible, [{filename="libcatala/date_en.catala_en";
                                  start_line=279; start_column=16;
                                  end_line=279; end_column=26;
                                  law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                                                 "Dates"]}], None)))
        | Optional.Present n -> n) in
    (let day_number : integer =
       (o_sub_int_int
          (o_add_int_int
             (o_add_int_int
                (o_add_int_int
                   (o_sub_int_int
                      (o_add_int_int year_number
                         (o_toint_rat
                            (o_div_int_int
                               {filename="libcatala/date_en.catala_en";
                                start_line=283; start_column=34;
                                end_line=283; end_column=35;
                                law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                                               "Dates"]} year_number
                               (integer_of_string "4"))))
                      (o_toint_rat
                         (o_div_int_int
                            {filename="libcatala/date_en.catala_en";
                             start_line=284; start_column=34;
                             end_line=284; end_column=37;
                             law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                                            "Dates"]} year_number
                            (integer_of_string "100"))))
                   (o_toint_rat
                      (o_div_int_int
                         {filename="libcatala/date_en.catala_en";
                          start_line=285; start_column=34;
                          end_line=285; end_column=37;
                          law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                                         "Dates"]} year_number
                         (integer_of_string "400")))) n_number)
             (get_day given_date))
          (o_mult_int_int (integer_of_string "7")
             (o_toint_rat
                (o_div_int_int
                   {filename="libcatala/date_en.catala_en";
                    start_line=295; start_column=9;
                    end_line=295; end_column=10;
                    law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                                   "Dates"]}
                   (o_add_int_int
                      (o_add_int_int
                         (o_add_int_int
                            (o_sub_int_int
                               (o_add_int_int year_number
                                  (o_toint_rat
                                     (o_div_int_int
                                        {filename="libcatala/date_en.catala_en";
                                         start_line=290; start_column=36;
                                         end_line=290; end_column=37;
                                         law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                                                        "Dates"]} year_number
                                        (integer_of_string "4"))))
                               (o_toint_rat
                                  (o_div_int_int
                                     {filename="libcatala/date_en.catala_en";
                                      start_line=291; start_column=36;
                                      end_line=291; end_column=39;
                                      law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                                                     "Dates"]} year_number
                                     (integer_of_string "100"))))
                            (o_toint_rat
                               (o_div_int_int
                                  {filename="libcatala/date_en.catala_en";
                                   start_line=292; start_column=36;
                                   end_line=292; end_column=39;
                                   law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                                                  "Dates"]} year_number
                                  (integer_of_string "400")))) n_number)
                      (get_day given_date)) (integer_of_string "7"))))) in
    (match
       ((List_en.nth_element)
          ([|(Day_of_week.Sunday); (Day_of_week.Monday);
             (Day_of_week.Tuesday); (Day_of_week.Wednesday);
             (Day_of_week.Thursday); (Day_of_week.Friday);
             (Day_of_week.Saturday)|])
          (o_add_int_int day_number (integer_of_string "1")))
     with
     | Optional.Absent -> (raise
         (Error (Impossible, [{filename="libcatala/date_en.catala_en";
                               start_line=300; start_column=14;
                               end_line=300; end_column=24;
                               law_headings=["Find the Day of the week for a given date (Tomohiko Sakamoto Algorithm)";
                                              "Dates"]}], None)))
     | Optional.Present d -> d)))))

let () =
  Catala_runtime.register_module "Date_en"
    [ "min", Stdlib.Obj.repr min;
      "max", Stdlib.Obj.repr max;
      "of_year_month_day", Stdlib.Obj.repr of_year_month_day;
      "to_year_month_day", Stdlib.Obj.repr to_year_month_day;
      "last_day_of_month", Stdlib.Obj.repr last_day_of_month;
      "month_to_integer", Stdlib.Obj.repr month_to_integer;
      "integer_to_month", Stdlib.Obj.repr integer_to_month;
      "is_old_enough_rounding_down",
        Stdlib.Obj.repr is_old_enough_rounding_down;
      "is_old_enough_rounding_up", Stdlib.Obj.repr is_old_enough_rounding_up;
      "last_day_of_year", Stdlib.Obj.repr last_day_of_year;
      "first_day_of_year", Stdlib.Obj.repr first_day_of_year;
      "first_day_of_month", Stdlib.Obj.repr first_day_of_month;
      "get_day", Stdlib.Obj.repr get_day;
      "get_month", Stdlib.Obj.repr get_month;
      "get_year", Stdlib.Obj.repr get_year;
      "is_young_enough_rounding_down",
        Stdlib.Obj.repr is_young_enough_rounding_down;
      "is_young_enough_rounding_up",
        Stdlib.Obj.repr is_young_enough_rounding_up;
      "day_of_week", Stdlib.Obj.repr day_of_week ]
    "CM0|15e33851|32e49b03|1be0e012"
