(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Date_internal
  = Date_internal
module List_fr = List_fr

module Mois : sig
  type t =
    | Janvier
    | Fevrier
    | Mars
    | Avril
    | Mai
    | Juin
    | Juillet
    | Aout
    | Septembre
    | Octobre
    | Novembre
    | Decembre
end

module Jour_de_la_semaine : sig
  type t = Lundi | Mardi | Mercredi | Jeudi | Vendredi | Samedi | Dimanche
end


(** Toplevel definition min *)
val min : date -> date -> date

(** Toplevel definition max *)
val max : date -> date -> date

(** Toplevel definition depuis_année_mois_jour *)
val depuis_annee_mois_jour : code_location -> integer -> integer ->
                               integer -> date

(** Toplevel definition vers_année_mois_jour *)
val vers_annee_mois_jour : date -> (integer * integer * integer)

(** Toplevel definition dernier_jour_du_mois *)
val dernier_jour_du_mois : date -> date

(** Toplevel definition mois_vers_entier *)
val mois_vers_entier : Mois.t -> integer

(** Toplevel definition entier_vers_mois *)
val entier_vers_mois : code_location -> integer -> Mois.t

(** Toplevel definition est_assez_âgé_arrondi_inférieur *)
val est_assez_age_arrondi_inferieur : date -> duration -> date -> bool

(** Toplevel definition est_assez_âgé_arrondi_supérieur *)
val est_assez_age_arrondi_superieur : date -> duration -> date -> bool

(** Toplevel definition dernier_jour_de_l_année *)
val dernier_jour_de_l_annee : date -> date

(** Toplevel definition premier_jour_de_l_année *)
val premier_jour_de_l_annee : date -> date

(** Toplevel definition premier_jour_du_mois *)
val premier_jour_du_mois : date -> date

(** Toplevel definition accès_jour *)
val acces_jour : date -> integer

(** Toplevel definition accès_mois *)
val acces_mois : date -> integer

(** Toplevel definition accès_année *)
val acces_annee : date -> integer

(** Toplevel definition est_assez_jeune_arrondi_inférieur *)
val est_assez_jeune_arrondi_inferieur : date -> duration -> date -> bool

(** Toplevel definition est_assez_jeune_arrondi_supérieur *)
val est_assez_jeune_arrondi_superieur : date -> duration -> date -> bool

(** Toplevel definition jour_de_la_semaine *)
val jour_de_la_semaine : date -> Jour_de_la_semaine.t
