(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Date_internal
  = Date_internal
module List_en = List_en

module Month : sig
  type t =
    | January
    | February
    | March
    | April
    | May
    | June
    | July
    | August
    | September
    | October
    | November
    | December
end

module Day_of_week : sig
  type t =
    | Monday
    | Tuesday
    | Wednesday
    | Thursday
    | Friday
    | Saturday
    | Sunday
end


(** Toplevel definition min *)
val min : date -> date -> date

(** Toplevel definition max *)
val max : date -> date -> date

(** Toplevel definition of_year_month_day *)
val of_year_month_day : code_location -> integer -> integer -> integer ->
                          date

(** Toplevel definition to_year_month_day *)
val to_year_month_day : date -> (integer * integer * integer)

(** Toplevel definition last_day_of_month *)
val last_day_of_month : date -> date

(** Toplevel definition month_to_integer *)
val month_to_integer : Month.t -> integer

(** Toplevel definition integer_to_month *)
val integer_to_month : code_location -> integer -> Month.t

(** Toplevel definition is_old_enough_rounding_down *)
val is_old_enough_rounding_down : date -> duration -> date -> bool

(** Toplevel definition is_old_enough_rounding_up *)
val is_old_enough_rounding_up : date -> duration -> date -> bool

(** Toplevel definition last_day_of_year *)
val last_day_of_year : date -> date

(** Toplevel definition first_day_of_year *)
val first_day_of_year : date -> date

(** Toplevel definition first_day_of_month *)
val first_day_of_month : date -> date

(** Toplevel definition get_day *)
val get_day : date -> integer

(** Toplevel definition get_month *)
val get_month : date -> integer

(** Toplevel definition get_year *)
val get_year : date -> integer

(** Toplevel definition is_young_enough_rounding_down *)
val is_young_enough_rounding_down : date -> duration -> date -> bool

(** Toplevel definition is_young_enough_rounding_up *)
val is_young_enough_rounding_up : date -> duration -> date -> bool

(** Toplevel definition day_of_week *)
val day_of_week : date -> Day_of_week.t
