(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Decimal_internal
  = Decimal_internal


(** Toplevel definition min *)
val min : decimal -> decimal -> decimal

(** Toplevel definition max *)
val max : decimal -> decimal -> decimal

(** Toplevel definition truncate *)
val truncate : decimal -> decimal

(** Toplevel definition round_to_decimal *)
val round_to_decimal : decimal -> integer -> decimal

(** Toplevel definition sum *)
val sum : (decimal array) -> decimal

(** Toplevel definition ceiling *)
val ceiling : decimal -> decimal -> decimal

(** Toplevel definition floor *)
val floor : decimal -> decimal -> decimal

(** Toplevel definition round_by_default *)
val round_by_default : decimal -> decimal

(** Toplevel definition round_by_excess *)
val round_by_excess : decimal -> decimal

(** Toplevel definition positive *)
val positive : decimal -> decimal
