(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Decimal_internal
  = Decimal_internal


(** Toplevel definition min *)
val min : decimal -> decimal -> decimal

(** Toplevel definition max *)
val max : decimal -> decimal -> decimal

(** Toplevel definition troncature *)
val troncature : decimal -> decimal

(** Toplevel definition arrondi_à_la_décimale *)
val arrondi_a_la_decimale : decimal -> integer -> decimal

(** Toplevel definition somme *)
val somme : (decimal array) -> decimal

(** Toplevel definition plafond *)
val plafond : decimal -> decimal -> decimal

(** Toplevel definition plancher *)
val plancher : decimal -> decimal -> decimal

(** Toplevel definition arrondi_par_défaut *)
val arrondi_par_defaut : decimal -> decimal

(** Toplevel definition arrondi_par_excès *)
val arrondi_par_exces : decimal -> decimal

(** Toplevel definition positif *)
val positif : decimal -> decimal
