(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime



(** Toplevel definition positif *)
val positif : duration -> duration

(** Toplevel definition somme *)
val somme : (duration array) -> duration
