(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime



(* Toplevel def positif *)
let positif : duration -> duration =
  fun (d: duration) ->
     if
      (o_gt_dur_dur
         {filename="libcatala/duration_fr.catala_fr";
          start_line=17; start_column=10; end_line=17; end_column=11;
          law_headings=["Fonctions utilitaires"; "Durées"]} d
         (duration_of_numbers (0) (0) (0))) then d else
      (duration_of_numbers (0) (0) (0))

(* Toplevel def somme *)
let somme : (duration array) -> duration =
  fun (l: duration array) ->
    o_fold (fun (total: duration) (x: duration) -> o_add_dur_dur total x)
      (duration_of_numbers (0) (0) (0)) l

let () =
  Catala_runtime.register_module "Duration_fr"
    [ "positif", Stdlib.Obj.repr positif;
      "somme", Stdlib.Obj.repr somme ]
    "CM0|15e33851|32e49b03|1af0d9fe"
