(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime



(* Toplevel def min *)
let min : integer -> integer -> integer =
  fun (n1: integer) (n2: integer) ->
     if (o_lte_int_int n1 n2) then n1 else n2

(* Toplevel def max *)
let max : integer -> integer -> integer =
  fun (n1: integer) (n2: integer) ->
     if (o_gte_int_int n1 n2) then n1 else n2

(* Toplevel def sum *)
let sum : (integer array) -> integer =
  fun (l: integer array) ->
    o_fold (fun (total: integer) (x: integer) -> o_add_int_int total x)
      (integer_of_string "0") l

(* Toplevel def ceiling *)
let ceiling : integer -> integer -> integer =
  fun (n: integer) (max_value: integer) -> min n max_value

(* Toplevel def floor *)
let floor : integer -> integer -> integer =
  fun (n: integer) (min_value: integer) -> max n min_value

(* Toplevel def positive *)
let positive : integer -> integer =
  fun (n: integer) -> floor n (integer_of_string "0")

let () =
  Catala_runtime.register_module "Integer_en"
    [ "min", Stdlib.Obj.repr min;
      "max", Stdlib.Obj.repr max;
      "sum", Stdlib.Obj.repr sum;
      "ceiling", Stdlib.Obj.repr ceiling;
      "floor", Stdlib.Obj.repr floor;
      "positive", Stdlib.Obj.repr positive ]
    "CM0|15e33851|32e49b03|1a7e2f37"
