(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime



(* Toplevel def min *)
let min : integer -> integer -> integer =
  fun (n1: integer) (n2: integer) ->  if (o_gt_int_int n1 n2) then n2 else n1

(* Toplevel def max *)
let max : integer -> integer -> integer =
  fun (n1: integer) (n2: integer) ->  if (o_gt_int_int n1 n2) then n1 else n2

(* Toplevel def somme *)
let somme : (integer array) -> integer =
  fun (l: integer array) ->
    o_fold (fun (total: integer) (x: integer) -> o_add_int_int total x)
      (integer_of_string "0") l

(* Toplevel def plafond *)
let plafond : integer -> integer -> integer =
  fun (variable: integer) (valeur_max: integer) -> min variable valeur_max

(* Toplevel def plancher *)
let plancher : integer -> integer -> integer =
  fun (variable: integer) (valeur_min: integer) -> max variable valeur_min

(* Toplevel def positif *)
let positif : integer -> integer =
  fun (variable: integer) -> plancher variable (integer_of_string "0")

let () =
  Catala_runtime.register_module "Integer_fr"
    [ "min", Stdlib.Obj.repr min;
      "max", Stdlib.Obj.repr max;
      "somme", Stdlib.Obj.repr somme;
      "plafond", Stdlib.Obj.repr plafond;
      "plancher", Stdlib.Obj.repr plancher;
      "positif", Stdlib.Obj.repr positif ]
    "CM0|15e33851|32e49b03|258d3d9c"
