(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime



(** Toplevel definition min *)
val min : integer -> integer -> integer

(** Toplevel definition max *)
val max : integer -> integer -> integer

(** Toplevel definition sum *)
val sum : (integer array) -> integer

(** Toplevel definition ceiling *)
val ceiling : integer -> integer -> integer

(** Toplevel definition floor *)
val floor : integer -> integer -> integer

(** Toplevel definition positive *)
val positive : integer -> integer
