(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime



(** Toplevel definition min *)
val min : integer -> integer -> integer

(** Toplevel definition max *)
val max : integer -> integer -> integer

(** Toplevel definition somme *)
val somme : (integer array) -> integer

(** Toplevel definition plafond *)
val plafond : integer -> integer -> integer

(** Toplevel definition plancher *)
val plancher : integer -> integer -> integer

(** Toplevel definition positif *)
val positif : integer -> integer
