(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module List_internal
  = List_internal


(** Toplevel definition séquence *)
val sequence : integer -> integer -> (integer array)

(** Toplevel definition nième_élément *)
val nieme_element : ('tt array) -> integer -> ('tt) Optional.t

(** Toplevel definition retire_nième_élément *)
val retire_nieme_element : ('tt array) -> integer -> ('tt array)

(** Toplevel definition retire_premier_élément *)
val retire_premier_element : ('tt array) -> ('tt array)

(** Toplevel definition retire_dernier_élément *)
val retire_dernier_element : ('tt array) -> ('tt array)

(** Toplevel definition inverse *)
val inverse : ('tt array) -> ('tt array)

(** Toplevel definition dernier_élément *)
val dernier_element : ('tt array) -> ('tt) Optional.t

(** Toplevel definition premier_élément *)
val premier_element : ('tt array) -> ('tt) Optional.t
