(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module List_internal
  = List_internal


(** Toplevel definition sequence *)
val sequence : integer -> integer -> (integer array)

(** Toplevel definition nth_element *)
val nth_element : ('tt array) -> integer -> ('tt) Optional.t

(** Toplevel definition remove_nth_element *)
val remove_nth_element : ('tt array) -> integer -> ('tt array)

(** Toplevel definition remove_first_element *)
val remove_first_element : ('tt array) -> ('tt array)

(** Toplevel definition remove_last_element *)
val remove_last_element : ('tt array) -> ('tt array)

(** Toplevel definition reverse *)
val reverse : ('tt array) -> ('tt array)

(** Toplevel definition last_element *)
val last_element : ('tt array) -> ('tt) Optional.t

(** Toplevel definition first_element *)
val first_element : ('tt array) -> ('tt) Optional.t
