(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "List_internal" "*external*" with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module List_internal, it may need recompiling"
module List_internal = List_internal


(* Toplevel def séquence *)
let sequence : integer -> integer -> (integer array) =
  fun (debut: integer) (fin: integer) -> (List_internal.sequence) debut fin

(* Toplevel def nième_élément *)
let nieme_element : ('tt array) -> integer -> ('tt) Optional.t =
  fun (l: 'tt array) (index: integer) -> (List_internal.nth_element) l index

(* Toplevel def retire_nième_élément *)
let retire_nieme_element : ('tt array) -> integer -> ('tt array) =
  fun (l: 'tt array) (index: integer) ->
    (List_internal.remove_nth_element) l index

(* Toplevel def retire_premier_élément *)
let retire_premier_element : ('tt array) -> ('tt array) =
  fun (l: 'tt array) ->
    (List_internal.remove_nth_element) l (integer_of_string "1")

(* Toplevel def retire_dernier_élément *)
let retire_dernier_element : ('tt array) -> ('tt array) =
  fun (l: 'tt array) -> (List_internal.remove_nth_element) l (o_length l)

(* Toplevel def inverse *)
let inverse : ('tt array) -> ('tt array) =
  fun (l: 'tt array) -> (List_internal.reverse) l

(* Toplevel def dernier_élément *)
let dernier_element : ('tt array) -> ('tt) Optional.t =
  fun (l: 'tt array) -> nieme_element l (o_length l)

(* Toplevel def premier_élément *)
let premier_element : ('tt array) -> ('tt) Optional.t =
  fun (l: 'tt array) -> nieme_element l (integer_of_string "1")

let () =
  Catala_runtime.register_module "List_fr"
    [ "s\195\169quence", Stdlib.Obj.repr sequence;
      "ni\195\168me_\195\169l\195\169ment", Stdlib.Obj.repr nieme_element;
      "retire_ni\195\168me_\195\169l\195\169ment",
        Stdlib.Obj.repr retire_nieme_element;
      "retire_premier_\195\169l\195\169ment",
        Stdlib.Obj.repr retire_premier_element;
      "retire_dernier_\195\169l\195\169ment",
        Stdlib.Obj.repr retire_dernier_element;
      "inverse", Stdlib.Obj.repr inverse;
      "dernier_\195\169l\195\169ment", Stdlib.Obj.repr dernier_element;
      "premier_\195\169l\195\169ment", Stdlib.Obj.repr premier_element ]
    "CM0|15e33851|32e49b03|19e8ab0c"
