(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "List_internal" "*external*" with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module List_internal, it may need recompiling"
module List_internal = List_internal


(* Toplevel def sequence *)
let sequence : integer -> integer -> (integer array) =
  fun (begin__1: integer) (end__1: integer) ->
    (List_internal.sequence) begin__1 end__1

(* Toplevel def nth_element *)
let nth_element : ('tt array) -> integer -> ('tt) Optional.t =
  fun (l: 'tt array) (index: integer) -> (List_internal.nth_element) l index

(* Toplevel def remove_nth_element *)
let remove_nth_element : ('tt array) -> integer -> ('tt array) =
  fun (l: 'tt array) (index: integer) ->
    (List_internal.remove_nth_element) l index

(* Toplevel def remove_first_element *)
let remove_first_element : ('tt array) -> ('tt array) =
  fun (l: 'tt array) ->
    (List_internal.remove_nth_element) l (integer_of_string "1")

(* Toplevel def remove_last_element *)
let remove_last_element : ('tt array) -> ('tt array) =
  fun (l: 'tt array) -> (List_internal.remove_nth_element) l (o_length l)

(* Toplevel def reverse *)
let reverse : ('tt array) -> ('tt array) =
  fun (l: 'tt array) -> (List_internal.reverse) l

(* Toplevel def last_element *)
let last_element : ('tt array) -> ('tt) Optional.t =
  fun (l: 'tt array) -> nth_element l (o_length l)

(* Toplevel def first_element *)
let first_element : ('tt array) -> ('tt) Optional.t =
  fun (l: 'tt array) -> nth_element l (integer_of_string "1")

let () =
  Catala_runtime.register_module "List_en"
    [ "sequence", Stdlib.Obj.repr sequence;
      "nth_element", Stdlib.Obj.repr nth_element;
      "remove_nth_element", Stdlib.Obj.repr remove_nth_element;
      "remove_first_element", Stdlib.Obj.repr remove_first_element;
      "remove_last_element", Stdlib.Obj.repr remove_last_element;
      "reverse", Stdlib.Obj.repr reverse;
      "last_element", Stdlib.Obj.repr last_element;
      "first_element", Stdlib.Obj.repr first_element ]
    "CM0|15e33851|32e49b03|24a3fb7d"
