(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Money_internal
  = Money_internal


(** Toplevel definition min *)
val min : money -> money -> money

(** Toplevel definition max *)
val max : money -> money -> money

(** Toplevel definition troncature *)
val troncature : money -> money

(** Toplevel definition arrondi_par_excès *)
val arrondi_par_exces : money -> money

(** Toplevel definition arrondi_par_défaut *)
val arrondi_par_defaut : money -> money

(** Toplevel definition arrondi_à_la_décimale *)
val arrondi_a_la_decimale : money -> integer -> money

(** Toplevel definition somme *)
val somme : (money array) -> money

(** Toplevel definition plafond *)
val plafond : money -> money -> money

(** Toplevel definition en_défaut *)
val en_defaut : money -> money -> money

(** Toplevel definition en_excès *)
val en_exces : money -> money -> money

(** Toplevel definition plancher *)
val plancher : money -> money -> money

(** Toplevel definition positif *)
val positif : money -> money
