(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Money_internal
  = Money_internal


(** Toplevel definition min *)
val min : money -> money -> money

(** Toplevel definition max *)
val max : money -> money -> money

(** Toplevel definition truncate *)
val truncate : money -> money

(** Toplevel definition round_by_excess *)
val round_by_excess : money -> money

(** Toplevel definition round_by_default *)
val round_by_default : money -> money

(** Toplevel definition round_to_decimal *)
val round_to_decimal : money -> integer -> money

(** Toplevel definition sum *)
val sum : (money array) -> money

(** Toplevel definition ceiling *)
val ceiling : money -> money -> money

(** Toplevel definition in_default *)
val in_default : money -> money -> money

(** Toplevel definition in_excess *)
val in_excess : money -> money -> money

(** Toplevel definition floor *)
val floor : money -> money -> money

(** Toplevel definition positive *)
val positive : money -> money
