(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Money_internal" "*external*" with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Money_internal, it may need recompiling"
module Money_internal = Money_internal


(* Toplevel def min *)
let min : money -> money -> money =
  fun (m1: money) (m2: money) ->  if (o_gt_mon_mon m1 m2) then m2 else m1

(* Toplevel def max *)
let max : money -> money -> money =
  fun (m1: money) (m2: money) ->  if (o_gt_mon_mon m1 m2) then m1 else m2

(* Toplevel def troncature *)
let troncature : money -> money =
  fun (a: money) ->
     if (o_eq_mon_mon a (money_of_cents_string "0")) then
      (money_of_cents_string "0") else
      ( if (o_gt_mon_mon a (money_of_cents_string "0")) then
         (o_round_mon (o_sub_mon_mon a (money_of_cents_string "50"))) else
         (o_round_mon (o_add_mon_mon a (money_of_cents_string "50"))))

(* Toplevel def arrondi_par_excès *)
let arrondi_par_exces : money -> money =
  fun (a: money) ->
     if (o_gte_mon_mon a (money_of_cents_string "0")) then
      (o_round_mon (o_add_mon_mon a (money_of_cents_string "49"))) else
      (o_round_mon (o_add_mon_mon a (money_of_cents_string "50")))

(* Toplevel def arrondi_par_défaut *)
let arrondi_par_defaut : money -> money =
  fun (a: money) ->
     if (o_gt_mon_mon a (money_of_cents_string "0")) then
      (o_round_mon (o_sub_mon_mon a (money_of_cents_string "50"))) else
      (o_round_mon (o_sub_mon_mon a (money_of_cents_string "49")))

(* Toplevel def arrondi_à_la_décimale *)
let arrondi_a_la_decimale : money -> integer -> money =
  fun (a: money) (nieme_decimale: integer) ->
    (Money_internal.round_to_decimal) a nieme_decimale

(* Toplevel def somme *)
let somme : (money array) -> money =
  fun (l: money array) ->
    o_fold (fun (total: money) (x: money) -> o_add_mon_mon total x)
      (money_of_cents_string "0") l

(* Toplevel def plafond *)
let plafond : money -> money -> money =
  fun (a: money) (valeur_max: money) -> min a valeur_max

(* Toplevel def en_défaut *)
let en_defaut : money -> money -> money =
  fun (a: money) (reference: money) ->
    max (money_of_cents_string "0") (o_sub_mon_mon reference a)

(* Toplevel def en_excès *)
let en_exces : money -> money -> money =
  fun (a: money) (reference: money) ->
    max (money_of_cents_string "0") (o_sub_mon_mon a reference)

(* Toplevel def plancher *)
let plancher : money -> money -> money =
  fun (a: money) (valeur_min: money) -> max a valeur_min

(* Toplevel def positif *)
let positif : money -> money =
  fun (a: money) -> plancher a (money_of_cents_string "0")

let () =
  Catala_runtime.register_module "Money_fr"
    [ "min", Stdlib.Obj.repr min;
      "max", Stdlib.Obj.repr max;
      "troncature", Stdlib.Obj.repr troncature;
      "arrondi_par_exc\195\168s", Stdlib.Obj.repr arrondi_par_exces;
      "arrondi_par_d\195\169faut", Stdlib.Obj.repr arrondi_par_defaut;
      "arrondi_\195\160_la_d\195\169cimale",
        Stdlib.Obj.repr arrondi_a_la_decimale;
      "somme", Stdlib.Obj.repr somme;
      "plafond", Stdlib.Obj.repr plafond;
      "en_d\195\169faut", Stdlib.Obj.repr en_defaut;
      "en_exc\195\168s", Stdlib.Obj.repr en_exces;
      "plancher", Stdlib.Obj.repr plancher;
      "positif", Stdlib.Obj.repr positif ]
    "CM0|15e33851|32e49b03|3ac0d3fb"
