(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Money_internal" "*external*" with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Money_internal, it may need recompiling"
module Money_internal = Money_internal


(* Toplevel def min *)
let min : money -> money -> money =
  fun (m1: money) (m2: money) ->  if (o_gt_mon_mon m1 m2) then m2 else m1

(* Toplevel def max *)
let max : money -> money -> money =
  fun (m1: money) (m2: money) ->  if (o_gt_mon_mon m1 m2) then m1 else m2

(* Toplevel def truncate *)
let truncate : money -> money =
  fun (m: money) ->
     if (o_eq_mon_mon m (money_of_cents_string "0")) then
      (money_of_cents_string "0") else
      ( if (o_gt_mon_mon m (money_of_cents_string "0")) then
         (o_round_mon (o_sub_mon_mon m (money_of_cents_string "50"))) else
         (o_round_mon (o_add_mon_mon m (money_of_cents_string "50"))))

(* Toplevel def round_by_excess *)
let round_by_excess : money -> money =
  fun (m: money) ->
     if (o_gte_mon_mon m (money_of_cents_string "0")) then
      (o_round_mon (o_add_mon_mon m (money_of_cents_string "49"))) else
      (o_round_mon (o_add_mon_mon m (money_of_cents_string "50")))

(* Toplevel def round_by_default *)
let round_by_default : money -> money =
  fun (m: money) ->
     if (o_gt_mon_mon m (money_of_cents_string "0")) then
      (o_round_mon (o_sub_mon_mon m (money_of_cents_string "50"))) else
      (o_round_mon (o_sub_mon_mon m (money_of_cents_string "49")))

(* Toplevel def round_to_decimal *)
let round_to_decimal : money -> integer -> money =
  fun (m: money) (nth_decimal: integer) ->
    (Money_internal.round_to_decimal) m nth_decimal

(* Toplevel def sum *)
let sum : (money array) -> money =
  fun (l: money array) ->
    o_fold (fun (total: money) (x: money) -> o_add_mon_mon total x)
      (money_of_cents_string "0") l

(* Toplevel def ceiling *)
let ceiling : money -> money -> money =
  fun (m: money) (max_value: money) -> min m max_value

(* Toplevel def in_default *)
let in_default : money -> money -> money =
  fun (m: money) (reference: money) ->
    max (money_of_cents_string "0") (o_sub_mon_mon reference m)

(* Toplevel def in_excess *)
let in_excess : money -> money -> money =
  fun (m: money) (reference: money) ->
    max (money_of_cents_string "0") (o_sub_mon_mon m reference)

(* Toplevel def floor *)
let floor : money -> money -> money =
  fun (m: money) (min_value: money) -> max m min_value

(* Toplevel def positive *)
let positive : money -> money =
  fun (m: money) -> floor m (money_of_cents_string "0")

let () =
  Catala_runtime.register_module "Money_en"
    [ "min", Stdlib.Obj.repr min;
      "max", Stdlib.Obj.repr max;
      "truncate", Stdlib.Obj.repr truncate;
      "round_by_excess", Stdlib.Obj.repr round_by_excess;
      "round_by_default", Stdlib.Obj.repr round_by_default;
      "round_to_decimal", Stdlib.Obj.repr round_to_decimal;
      "sum", Stdlib.Obj.repr sum;
      "ceiling", Stdlib.Obj.repr ceiling;
      "in_default", Stdlib.Obj.repr in_default;
      "in_excess", Stdlib.Obj.repr in_excess;
      "floor", Stdlib.Obj.repr floor;
      "positive", Stdlib.Obj.repr positive ]
    "CM0|15e33851|32e49b03|22cf526d"
