(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Date_fr" "CM0|15e33851|32e49b03|3096d497"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Date_fr, it may need recompiling"
module Date_fr = Date_fr

module MoisAnnee = struct
  type t = {nom_mois: Date_fr.Mois.t; annee: integer}
end


(* Toplevel def depuis_date *)
let depuis_date : date -> MoisAnnee.t =
  fun (d: date) ->
    {MoisAnnee.nom_mois =
       ((Date_fr.entier_vers_mois)
          ({filename="libcatala/monthyear_fr.catala_fr";
            start_line=18; start_column=20; end_line=18; end_column=38;
            law_headings=["Mois d'années spécifiques"]})
          ((Date_fr.acces_mois) d));
       MoisAnnee.annee = ((Date_fr.acces_annee) d)}

(* Toplevel def premier_jour_du_mois *)
let premier_jour_du_mois : MoisAnnee.t -> date =
  fun (m: MoisAnnee.t) ->
    (Date_fr.depuis_annee_mois_jour)
      ({filename="libcatala/monthyear_fr.catala_fr";
        start_line=26; start_column=5; end_line=26; end_column=29;
        law_headings=["Mois d'années spécifiques"]}) (m.MoisAnnee.annee)
      ((Date_fr.mois_vers_entier) (m.MoisAnnee.nom_mois)) (integer_of_string
      "1")

(* Toplevel def dernier_jour_du_mois *)
let dernier_jour_du_mois : MoisAnnee.t -> date =
  fun (m: MoisAnnee.t) ->
    (Date_fr.dernier_jour_du_mois)
      ((Date_fr.depuis_annee_mois_jour)
         ({filename="libcatala/monthyear_fr.catala_fr";
           start_line=34; start_column=8; end_line=34; end_column=32;
           law_headings=["Mois d'années spécifiques"]}) (m.MoisAnnee.annee)
         ((Date_fr.mois_vers_entier) (m.MoisAnnee.nom_mois))
         (integer_of_string "1"))

(* Toplevel def est_pendant_ou_après_le_mois *)
let est_pendant_ou_apres_le_mois : MoisAnnee.t -> date -> bool =
  fun (m: MoisAnnee.t) (d: date) -> o_gte_dat_dat d (premier_jour_du_mois m)

(* Toplevel def est_avant_le_mois *)
let est_avant_le_mois : MoisAnnee.t -> date -> bool =
  fun (m: MoisAnnee.t) (d: date) -> o_lt_dat_dat d (premier_jour_du_mois m)

(* Toplevel def est_avant_ou_pendant_le_mois *)
let est_avant_ou_pendant_le_mois : MoisAnnee.t -> date -> bool =
  fun (m: MoisAnnee.t) (d: date) -> o_lte_dat_dat d (dernier_jour_du_mois m)

(* Toplevel def est_après_le_mois *)
let est_apres_le_mois : MoisAnnee.t -> date -> bool =
  fun (m: MoisAnnee.t) (d: date) -> o_gt_dat_dat d (dernier_jour_du_mois m)

(* Toplevel def est_dans_le_mois *)
let est_dans_le_mois : MoisAnnee.t -> date -> bool =
  fun (m: MoisAnnee.t) (d: date) ->
    (est_avant_ou_pendant_le_mois m d) && (est_pendant_ou_apres_le_mois m d)

let () =
  Catala_runtime.register_module "MonthYear_fr"
    [ "depuis_date", Stdlib.Obj.repr depuis_date;
      "premier_jour_du_mois", Stdlib.Obj.repr premier_jour_du_mois;
      "dernier_jour_du_mois", Stdlib.Obj.repr dernier_jour_du_mois;
      "est_pendant_ou_apr\195\168s_le_mois",
        Stdlib.Obj.repr est_pendant_ou_apres_le_mois;
      "est_avant_le_mois", Stdlib.Obj.repr est_avant_le_mois;
      "est_avant_ou_pendant_le_mois",
        Stdlib.Obj.repr est_avant_ou_pendant_le_mois;
      "est_apr\195\168s_le_mois", Stdlib.Obj.repr est_apres_le_mois;
      "est_dans_le_mois", Stdlib.Obj.repr est_dans_le_mois ]
    "CM0|15e33851|32e49b03|3ebed8a5"
