(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Date_fr
  = Date_fr

module MoisAnnee : sig
  type t = {nom_mois: Date_fr.Mois.t; annee: integer}
end


(** Toplevel definition depuis_date *)
val depuis_date : date -> MoisAnnee.t

(** Toplevel definition premier_jour_du_mois *)
val premier_jour_du_mois : MoisAnnee.t -> date

(** Toplevel definition dernier_jour_du_mois *)
val dernier_jour_du_mois : MoisAnnee.t -> date

(** Toplevel definition est_pendant_ou_après_le_mois *)
val est_pendant_ou_apres_le_mois : MoisAnnee.t -> date -> bool

(** Toplevel definition est_avant_le_mois *)
val est_avant_le_mois : MoisAnnee.t -> date -> bool

(** Toplevel definition est_avant_ou_pendant_le_mois *)
val est_avant_ou_pendant_le_mois : MoisAnnee.t -> date -> bool

(** Toplevel definition est_après_le_mois *)
val est_apres_le_mois : MoisAnnee.t -> date -> bool

(** Toplevel definition est_dans_le_mois *)
val est_dans_le_mois : MoisAnnee.t -> date -> bool
