(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Date_en
  = Date_en

module MonthYear : sig
  type t = {year_number: integer; month_name: Date_en.Month.t}
end


(** Toplevel definition from_date *)
val from_date : date -> MonthYear.t

(** Toplevel definition first_day_of_month *)
val first_day_of_month : MonthYear.t -> date

(** Toplevel definition last_day_of_month *)
val last_day_of_month : MonthYear.t -> date

(** Toplevel definition is_during_or_after_month *)
val is_during_or_after_month : MonthYear.t -> date -> bool

(** Toplevel definition is_before_the_month *)
val is_before_the_month : MonthYear.t -> date -> bool

(** Toplevel definition is_before_or_during_month *)
val is_before_or_during_month : MonthYear.t -> date -> bool

(** Toplevel definition is_after_the_month *)
val is_after_the_month : MonthYear.t -> date -> bool

(** Toplevel definition is_in_the_month *)
val is_in_the_month : MonthYear.t -> date -> bool
