(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Date_en" "CM0|15e33851|32e49b03|1be0e012"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Date_en, it may need recompiling"
module Date_en = Date_en

module MonthYear = struct
  type t = {year_number: integer; month_name: Date_en.Month.t}
end


(* Toplevel def from_date *)
let from_date : date -> MonthYear.t =
  fun (d: date) ->
    {MonthYear.year_number = ((Date_en.get_year) d);
       MonthYear.month_name =
         ((Date_en.integer_to_month)
            ({filename="libcatala/monthyear_en.catala_en";
              start_line=18; start_column=22; end_line=18; end_column=40;
              law_headings=["Months of specific years"]})
            ((Date_en.get_month) d))}

(* Toplevel def first_day_of_month *)
let first_day_of_month : MonthYear.t -> date =
  fun (m: MonthYear.t) ->
    (Date_en.of_year_month_day)
      ({filename="libcatala/monthyear_en.catala_en";
        start_line=26; start_column=5; end_line=26; end_column=24;
        law_headings=["Months of specific years"]}) (m.MonthYear.year_number)
      ((Date_en.month_to_integer) (m.MonthYear.month_name))
      (integer_of_string "1")

(* Toplevel def last_day_of_month *)
let last_day_of_month : MonthYear.t -> date =
  fun (m: MonthYear.t) ->
    (Date_en.last_day_of_month)
      ((Date_en.of_year_month_day)
         ({filename="libcatala/monthyear_en.catala_en";
           start_line=34; start_column=8; end_line=34; end_column=27;
           law_headings=["Months of specific years"]})
         (m.MonthYear.year_number)
         ((Date_en.month_to_integer) (m.MonthYear.month_name))
         (integer_of_string "1"))

(* Toplevel def is_during_or_after_month *)
let is_during_or_after_month : MonthYear.t -> date -> bool =
  fun (m: MonthYear.t) (d: date) -> o_gte_dat_dat d (first_day_of_month m)

(* Toplevel def is_before_the_month *)
let is_before_the_month : MonthYear.t -> date -> bool =
  fun (m: MonthYear.t) (d: date) -> o_lt_dat_dat d (first_day_of_month m)

(* Toplevel def is_before_or_during_month *)
let is_before_or_during_month : MonthYear.t -> date -> bool =
  fun (m: MonthYear.t) (d: date) -> o_lte_dat_dat d (last_day_of_month m)

(* Toplevel def is_after_the_month *)
let is_after_the_month : MonthYear.t -> date -> bool =
  fun (m: MonthYear.t) (d: date) -> o_gt_dat_dat d (last_day_of_month m)

(* Toplevel def is_in_the_month *)
let is_in_the_month : MonthYear.t -> date -> bool =
  fun (m: MonthYear.t) (d: date) ->
    (is_before_or_during_month m d) && (is_during_or_after_month m d)

let () =
  Catala_runtime.register_module "MonthYear_en"
    [ "from_date", Stdlib.Obj.repr from_date;
      "first_day_of_month", Stdlib.Obj.repr first_day_of_month;
      "last_day_of_month", Stdlib.Obj.repr last_day_of_month;
      "is_during_or_after_month", Stdlib.Obj.repr is_during_or_after_month;
      "is_before_the_month", Stdlib.Obj.repr is_before_the_month;
      "is_before_or_during_month", Stdlib.Obj.repr is_before_or_during_month;
      "is_after_the_month", Stdlib.Obj.repr is_after_the_month;
      "is_in_the_month", Stdlib.Obj.repr is_in_the_month ]
    "CM0|15e33851|32e49b03|3436d8e8"
