(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Period_internal
  = Period_internal
module Date_fr = Date_fr

module Periode : sig
  type t = {debut: date; fin: date}
end


(** Toplevel definition depuis_mois_et_année *)
val depuis_mois_et_annee : Date_fr.Mois.t -> integer -> Periode.t

(** Toplevel definition depuis_année *)
val depuis_annee : integer -> Periode.t

(** Toplevel definition valide *)
val valide : Periode.t -> bool

(** Toplevel definition durée *)
val duree : Periode.t -> duration

(** Toplevel definition sont_adjacentes *)
val sont_adjacentes : Periode.t -> Periode.t -> bool

(** Toplevel definition union *)
val union : Periode.t -> Periode.t -> Periode.t

(** Toplevel definition englobe *)
val englobe : Periode.t -> Periode.t -> bool

(** Toplevel definition est_contenue *)
val est_contenue : Periode.t -> date -> bool

(** Toplevel definition est_avant *)
val est_avant : Periode.t -> date -> bool

(** Toplevel definition est_après *)
val est_apres : Periode.t -> date -> bool

(** Toplevel definition intersection *)
val intersection : Periode.t -> Periode.t -> (Periode.t) Optional.t

(** Toplevel definition trouve_période *)
val trouve_periode : (Periode.t array) -> date -> (Periode.t) Optional.t

(** Toplevel definition chevauche *)
val chevauche : Periode.t -> Periode.t -> bool

(** Toplevel definition divise_par_année *)
val divise_par_annee : Date_fr.Mois.t -> Periode.t -> (Periode.t array)

(** Toplevel definition divise_par_mois *)
val divise_par_mois : Periode.t -> (Periode.t array)

(** Toplevel definition tri_par_date *)
val tri_par_date : ((Periode.t * 'tt) array) -> ((Periode.t * 'tt) array)
