(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Period_internal
  = Period_internal
module Date_en = Date_en

module Period : sig
  type t = {begin__1: date; end__1: date}
end


(** Toplevel definition of_month_and_year *)
val of_month_and_year : Date_en.Month.t -> integer -> Period.t

(** Toplevel definition of_year *)
val of_year : integer -> Period.t

(** Toplevel definition valid *)
val valid : Period.t -> bool

(** Toplevel definition duration *)
val duration : Period.t -> duration

(** Toplevel definition are_adjacent *)
val are_adjacent : Period.t -> Period.t -> bool

(** Toplevel definition join *)
val join : Period.t -> Period.t -> Period.t

(** Toplevel definition covers *)
val covers : Period.t -> Period.t -> bool

(** Toplevel definition is_contained *)
val is_contained : Period.t -> date -> bool

(** Toplevel definition is_before *)
val is_before : Period.t -> date -> bool

(** Toplevel definition is_after *)
val is_after : Period.t -> date -> bool

(** Toplevel definition intersection *)
val intersection : Period.t -> Period.t -> (Period.t) Optional.t

(** Toplevel definition find_period *)
val find_period : (Period.t array) -> date -> (Period.t) Optional.t

(** Toplevel definition overlaps *)
val overlaps : Period.t -> Period.t -> bool

(** Toplevel definition split_by_year *)
val split_by_year : Date_en.Month.t -> Period.t -> (Period.t array)

(** Toplevel definition split_by_month *)
val split_by_month : Period.t -> (Period.t array)

(** Toplevel definition sort_by_date *)
val sort_by_date : ((Period.t * 'tt) array) -> ((Period.t * 'tt) array)
