(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Date_fr" "CM0|15e33851|32e49b03|3096d497"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Date_fr, it may need recompiling"
module Date_fr = Date_fr
let () =
  match Catala_runtime.check_module "List_fr" "CM0|15e33851|32e49b03|19e8ab0c"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module List_fr, it may need recompiling"
module List_fr = List_fr
let () =
  match Catala_runtime.check_module "Duration_fr" "CM0|15e33851|32e49b03|1af0d9fe"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Duration_fr, it may need recompiling"
module Duration_fr = Duration_fr
let () =
  match Catala_runtime.check_module "MonthYear_fr" "CM0|15e33851|32e49b03|3ebed8a5"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module MonthYear_fr, it may need recompiling"
module MonthYear_fr = MonthYear_fr
let () =
  match Catala_runtime.check_module "Period_fr" "CM0|15e33851|32e49b03|17de7a19"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Period_fr, it may need recompiling"
module Period_fr = Period_fr
let () =
  match Catala_runtime.check_module "Money_fr" "CM0|15e33851|32e49b03|3ac0d3fb"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Money_fr, it may need recompiling"
module Money_fr = Money_fr
let () =
  match Catala_runtime.check_module "Integer_fr" "CM0|15e33851|32e49b03|258d3d9c"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Integer_fr, it may need recompiling"
module Integer_fr = Integer_fr
let () =
  match Catala_runtime.check_module "Decimal_fr" "CM0|15e33851|32e49b03|3af7d45f"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Decimal_fr, it may need recompiling"
module Decimal_fr = Decimal_fr


let () =
  Catala_runtime.register_module "Stdlib_fr"
    [  ]
    "CM0|15e33851|32e49b03|1ee23d02"
