(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


let () =
  match Catala_runtime.check_module "Date_en" "CM0|15e33851|32e49b03|1be0e012"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Date_en, it may need recompiling"
module Date_en = Date_en
let () =
  match Catala_runtime.check_module "List_en" "CM0|15e33851|32e49b03|24a3fb7d"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module List_en, it may need recompiling"
module List_en = List_en
let () =
  match Catala_runtime.check_module "Duration_en" "CM0|15e33851|32e49b03|150e2ea0"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Duration_en, it may need recompiling"
module Duration_en = Duration_en
let () =
  match Catala_runtime.check_module "MonthYear_en" "CM0|15e33851|32e49b03|3436d8e8"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module MonthYear_en, it may need recompiling"
module MonthYear_en = MonthYear_en
let () =
  match Catala_runtime.check_module "Period_en" "CM0|15e33851|32e49b03|16c825d2"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Period_en, it may need recompiling"
module Period_en = Period_en
let () =
  match Catala_runtime.check_module "Money_en" "CM0|15e33851|32e49b03|22cf526d"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Money_en, it may need recompiling"
module Money_en = Money_en
let () =
  match Catala_runtime.check_module "Integer_en" "CM0|15e33851|32e49b03|1a7e2f37"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Integer_en, it may need recompiling"
module Integer_en = Integer_en
let () =
  match Catala_runtime.check_module "Decimal_en" "CM0|15e33851|32e49b03|2ee7fc57"
    with
  | Ok () -> ()
  | Error h -> failwith "Hash mismatch for module Decimal_en, it may need recompiling"
module Decimal_en = Decimal_en


let () =
  Catala_runtime.register_module "Stdlib_en"
    [  ]
    "CM0|15e33851|32e49b03|165aeded"
