(** This file has been generated by the Catala compiler, do not edit! *)

[@@@ocaml.warning "-4-26-27-32-33-34-37-41-42-69"]

open Catala_runtime


module Date_fr
  = Date_fr
module List_fr = List_fr
module Duration_fr = Duration_fr
module MonthYear_fr = MonthYear_fr
module Period_fr = Period_fr
module Money_fr = Money_fr
module Integer_fr = Integer_fr
module Decimal_fr = Decimal_fr

