name: 'Send system notification'
description: 'Send a system notification to a chat application |
  like Slack or Microsoft Teams. |
  The available notification channels are defined in the infra/project-config/ |
  Terraform module in system-notifications.tf.'

inputs:
  channel:
    description: 'Name of channel to use. Must be defined in /infra/project-config'
  message:
    description: 'Message to send'
runs:
  using: "composite"
  steps:
    - name: Get channel configuration
      id: get-channel-type
      run: |
        echo "Get channel type for channel=${{ inputs.channel }}"

        terraform -chdir="infra/project-config" init > /dev/null
        terraform -chdir="infra/project-config" apply -auto-approve > /dev/null

        channel_config="$(terraform -chdir="infra/project-config" output -json system_notifications_config | jq -r ".${{ inputs.channel }}")"

        channel_type="$(echo "${channel_config}" | jq -r ".type")"
        echo "Channel type: ${channel_type}"
        echo "channel_type=${channel_type}" >> "$GITHUB_OUTPUT"

        if [[ "${channel_type}" == "slack" ]]; then
          channel_id_secret_name="$(echo "${channel_config}" | jq -r ".channel_id_secret_name")"
          echo "Channel ID secret name: ${channel_id_secret_name}"
          echo "CHANNEL_ID_SECRET_NAME=${channel_id_secret_name}" >> "$GITHUB_ENV"

          slack_token_secret_name="$(echo "${channel_config}" | jq -r ".slack_token_secret_name")"
          echo "Slack token secret name: ${slack_token_secret_name}"
          echo "SLACK_TOKEN_SECRET_NAME=${slack_token_secret_name}" >> "$GITHUB_ENV"
        else
      shell: bash

    - name: Get Slack credentials
      id: get-slack-credentials
      if: ${{ steps.get-channel-type.outputs.channel_type == 'slack' }}
      run: |
        echo "Setting env vars SLACK_BOT_TOKEN and SLACK_CHANNEL_ID..."
        echo "SLACK_BOT_TOKEN='${{ secrets[env.SLACK_TOKEN_SECRET_NAME] }}'" >> "$GITHUB_ENV"
        echo "SLACK_CHANNEL_ID='${{ secrets[env.CHANNEL_ID_SECRET_NAME] }}'" >> "$GITHUB_ENV"
      shell: bash

    - name: Send Slack message
      if: ${{ steps.get-channel-type.outputs.channel_type == "slack" }}
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ env.SLACK_BOT_TOKEN }}
        payload: |
          channel: ${{ env.SLACK_CHANNEL_ID }}
          text: ${{ inputs.message }}
