name: Check GitHub Actions AWS Authentication

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build release
        run: make release-build
      - name: Publish release
        run: make release-publish
