name: Deploy app-nextjs
# Need to set a default value for when the workflow is triggered from a git push
# which bypasses the default configuration for inputs
run-name: Deploy ${{inputs.version || 'main' }} to app-nextjs ${{ inputs.environment || 'dev' }}

on:
  # !! Once you've set up the dev environment and are ready to enable continuous
  # deployment, run:
  #
  # nava-platform infra update --answers-only --data app_has_dev_env_setup=true .
  #
  # to enable these lines. They are here as comments for context.
  #
  # push:
  #   branches:
  #     - "main"
  #   paths:
  #     - "app-nextjs/**"
  #     - "bin/**"
  #     - "infra/**"
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod
      version:
        required: true
        default: "main"
        description: Tag or branch or SHA to deploy

jobs:
  deploy:
    name: " " # GitHub UI is noisy when calling reusable workflows, so use whitespace for name to reduce noise
    uses: ./.github/workflows/deploy.yml
    with:
      app_name: "app-nextjs"
      environment: ${{ inputs.environment || 'dev' }}
      version: ${{ inputs.version || 'main' }}
    secrets: inherit
