name: Deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/**'
      - 'bin/**'
      - 'infra/**'
  workflow_dispatch:
    inputs:
      environment:
        description: "environment input"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  ENVIRONMENT: ${{ inputs.environment || 'dev' }}

# Need to repeat the expression since env.ENV_NAME is not accessible in this context
concurrency: cd-${{ inputs.environment || 'dev' }}

jobs:
  database-migrations:
    name: Run database migrations
    uses: ./.github/workflows/database-migrations.yml
    with:
      environment: ${{ inputs.environment }}
  deploy:
    runs-on: ubuntu-latest
    needs: [database-migrations]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Build release
        run: make release-build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::430004246987:role/platform-test-github-actions
          aws-region: us-east-1

      - name: Publish release
        run: make release-publish

      - name: Deploy release
        run: make release-deploy ENVIRONMENT="$ENVIRONMENT"
