name: Deploy

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'app/**'
      - 'bin/**'
      - 'infra/**'
  workflow_dispatch:
    inputs:
      environment:
        description: "environment input"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  ENVIRONMENT: ${{ inputs.environment || 'dev' }}

# Need to repeat the expression since env.ENV_NAME is not accessible in this context
concurrency: cd-${{ inputs.environment || 'dev' }}

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      ref: ${{ github.ref }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy release
        run: make release-deploy ENVIRONMENT="$ENVIRONMENT"
