name: Deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/**'
      - 'bin/**'
      - 'infra/**'
  workflow_dispatch:
    inputs:
      environment:
        description: "environment input"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  ENVIRONMENT: ${{ inputs.environment || 'dev' }}

# Need to repeat the expression since env.ENV_NAME is not accessible in this context
concurrency: cd-${{ inputs.environment || 'dev' }}

jobs:
  build-and-publish:
    name: Build
    uses: ./.github/workflows/build-and-publish.yml
    with:
      ref: ${{ github.ref }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-publish]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::430004246987:role/platform-test-github-actions
          aws-region: us-east-1
      - name: Deploy release
        run: make release-deploy ENVIRONMENT="$ENVIRONMENT"
