# This workflow checks the status of infrastructure deployments to see whether
# infrastructure code configuration matches the actual state of the infrastructure.
# It does this by checking that Terraform plans show an empty diff (no changes)
# across all root modules and backend configurations.
name: Check infra deploy status

on:
  workflow_dispatch:
  schedule:
    # Run every day at 00:00 UTC
    - cron: "0 0 * * *"
  pull_request:

jobs:
  collect-root-module-configurations:
    name: Collect root module configurations
    runs-on: ubuntu-latest
    outputs:
      root_module_configs: ${{ steps.collect-root-module-configurations.outputs.root_module_configs }}
    steps:
      - uses: actions/checkout@v4
      - name: Collect root module configurations
        id: collect-root-module-configurations
        run: |
          root_module_configs="$(node ./bin/root-module-configurations.js)"
          echo "root_module_configs=${root_module_configs}" >> "$GITHUB_OUTPUT"
  check:
    name: Check ${{ matrix.rootModule }} ${{ matrix.backendConfigName }}
    runs-on: ubuntu-latest
    needs: collect-root-module-configurations
    strategy:
      matrix:
        include: ${{ fromJson(needs.collect-root-module-configurations.outputs.root_module_configs) }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3
          terraform_wrapper: false
      - name: Check Terraform plan
        run: |
          terraform -chdir="${{ matrix.rootModule }}" -input=false -reconfigure -backend-config="${{ matrix.backendConfigName }}.s3.tfbackend"
          terraform -chdir="${{ matrix.rootModule }}" plan -input=false -detailed-exitcode
