name: CI Infra Service Checks - app

on:
  push:
    branches:
      - main
    paths:
      - infra/app/service/**
      - infra/modules/**
      - infra/test/**
      - .github/workflows/ci-app-infra-service.yml
  pull_request:
    paths:
      - infra/app/service/**
      - infra/modules/**
      - infra/test/**
      - .github/workflows/ci-app-infra-service.yml
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: "main"
        description: Tag or branch or SHA to test

jobs:
  # `make infra-test-service` will build and publish the release itself, but
  #  doing it explicitly with the re-usable workflow helps avoid race conditions
  build-and-publish:
    name: Build
    uses: ./.github/workflows/build-and-publish.yml
    with:
      app_name: app
      ref: ${{ inputs.version || github.event.pull_request.head.sha || 'main' }}

  infra-test-e2e:
    name: Test service
    runs-on: ubuntu-latest
    needs: [build-and-publish]

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: ./.github/actions/setup-terraform

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.19.0"

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: app
          # Run infra CI on dev environment
          environment: dev

      - name: Run Terratest
        run: make infra-test-service APP_NAME=app
