name: CI App PR Environment Create
on:
  pull_request:
    types: [opened, reopened]
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Call PR Environment Create Workflow
        uses: ./.github/workflows/pr-environment-create.yml
        with:
          app_name: "app"
          environment: "dev"
