name: CI app-documentai-api

on:
  push:
    branches:
      - main
    paths:
      - app-documentai-api/**
      - .github/workflows/ci-app-documentai-api.yml
  pull_request:
    paths:
      - app-documentai-api/**
      - .github/workflows/ci-app-documentai-api.yml

defaults:
  run:
    working-directory: ./app-documentai-api

jobs:
  # As an enhancement, it is possible to share the built docker image and share
  # it across jobs as described in:
  # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: make build

      - name: Check formatting
        run: make format

      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: make build

      - name: Run tests
        run: |
          make test-audit
          make test-coverage
