# This workflow runs vulnerability scans on the app using several tools.

name: CI Vulnerability Scans - app

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/vulnerability-scans.yml
      - .github/workflows/ci-app-vulnerability-scans.yml
  pull_request:
    paths:
      - app/**
      - .grype.yml
      - .hadolint.yaml
      - .trivyignore
      - .github/workflows/vulnerability-scans.yml
      - .github/workflows/ci-app-vulnerability-scans.yml
  workflow_dispatch:

jobs:
  vulnerability-scans:
    name: Vulnerability Scans
    uses: ./.github/workflows/vulnerability-scans.yml
    with:
      app_name: "app"
  notify:
    name: Notify
    needs: vulnerability-scans
    if: failure() && github.event_name == 'push'
    uses: ./.github/workflows/send-system-notification.yml
    with:
      channel: "workflow-failures"
      message: "⚠️ [Vulnerabilities found in app](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
    secrets: inherit
