name: CI App PR Environment Destroy
on:
  pull_request:
    types: [closed]
jobs:
  destroy:
    name: App
    uses: ./.github/workflows/pr-environment-destroy.yml
    with:
      app_name: "app"
      environment: "dev"
