# This workflow runs CI checks for documentation, including linting markdown files.

name: CI Documentation Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # This is the GitHub Actions-friendly port of the linter used in the Makefile.
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          use-quiet-mode: "yes" # errors only.
          config-file: ".github/workflows/markdownlint-config.json"

  notify:
    name: Notify
    needs: lint-markdown
    if: failure()
    uses: ./.github/workflows/send-system-notification.yml
    with:
      channel: "workflow-failures"
      message: "⚠️ [Documentation checks failed](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
    secrets: inherit
