name: CI Infra Database Checks

on:
  push:
    branches:
      - main
    paths:
      - infra/*/database/**
      - test/**
      - .github/workflows/ci-infra-database.yml
  pull_request:
    paths:
      - infra/*/database/**
      - test/**
      - .github/workflows/ci-infra-database.yml

jobs:
  infra-test-e2e:
    name: Test database
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false

      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: app
          # Run infra CI on dev environment
          environment: dev

      - name: Run Terratest
        run: make infra-test-database
