name: PR Environment Update
run-name: Update PR Environment ${{ github.event.number }}
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    with:
      app_name: ${{ inputs.app_name }}
      ref: ${{ github.sha }}
  update:
    needs: [build-and-publish]
    runs-on: ubuntu-latest
    concurrency: pr-environment-${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: ./.github/actions/configure-aws-credentials
        with:
          app_name: ${{ inputs.app_name }}
          environment: ${{ inputs.environment }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3
          terraform_wrapper: false
      - name: Initialize Terraform with backend for environment
        run: terraform -chdir=infra/${{ inputs.app_name }}/service init -backend-config=${{ inputs.environment }}.s3.tfbackend
      - name: Select Terraform workspace for PR
        run: terraform -chdir=infra/${{ inputs.app_name }}/service workspace select p-${{ github.event.number }}
      - name: Update service layer
        run: terraform -chdir=infra/${{ inputs.app_name }}/service apply -input=false -auto-approve -var=image_tag=${{ github.sha }}
